jadwalku/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('tambah', views.message_post),
    path('<int:num>', views.matkul),
    path('delete/<int:num>', views.delete)
]

lab_1/urls.py
from django.contrib import admin
from django.urls import path

from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()

myweb/urls.py
from django.contrib import admin
from django.urls import path, include, register_converter
from django.conf import settings
from django.conf.urls.static import static
from .views import index, time, timezoned

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include('portfolio.urls')),
    path('', index, name='index'),
    path('story_1/',include('lab_1.urls')),
    path('time/', time),
    path('time/<int:zone>', timezoned),
    path('time/<str:zone>', timezoned),
    path('schedule/',include('jadwalku.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from .views import index, hobby

urlpatterns = [
    path('', index, name='index'),
    path('hobby', hobby, name='hobby'),
]

jadwalku/models.py
from django.db import models
from django.forms import ModelForm

class Schedule(models.Model):
    matkul = models.CharField(max_length=40)
    pengajar = models.CharField(max_length=40)
    sks = models.IntegerField()
    desc = models.CharField(max_length=1000)
    term = models.CharField(max_length=10)
    ruangan = models.CharField(max_length=16)

    def __str__(self):
        return self.matkul

class Assignment(models.Model):
    tugas = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    deadline =  models.DateTimeField()
    judul_tugas = models.CharField(max_length=25, default="")

    def __str__(self):
        return self.judul_tugas

    class Meta:
        ordering = ['deadline']

portfolio/models.py
from django.db import models

# Create your models here.

jadwalku/forms.py
from django import forms
from .models import Schedule

class Schedule_Form(forms.ModelForm):
    # matkul = forms.CharField(label='Matkul', required=True,
    #     max_length=40,
    #     widget=forms.TextInput)
    # pengajar = forms.CharField(label='Dosen Pengajar', required=True,
    #     max_length=40,
    #     widget=forms.TextInput)
    # sks = forms.IntegerField(label='Jumlah SKS', required=True)
    # desc = forms.CharField(label='Tambahkan deskripsi jika diperlukan', required=False, widget=forms.TextInput)
    # term = forms.CharField(label='Term', required=True,
    #     max_length=10, widget=forms.TextInput)
    # ruangan = forms.CharField(label='Ruangan', required=True,
    #     max_length=16, widget=forms.Textarea)
    class Meta:
        model = Schedule
        fields = '__all__'

jadwalku/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import Schedule_Form
from .models import Schedule, Assignment
from datetime import datetime, timedelta
from time import mktime
import pytz

def index(request):
    items = Schedule.objects.all()
    context = {'items':items}
    return render(request, 'jadwalku/jadwalfull.html', context)

def matkul(request, num):
    items = Schedule.objects.get(id=num)
    tugas = Assignment.objects.filter(tugas = items)
    context = {'items':items, 'tugas':tugas}
    deadlinelist = []
    deadlinetype = []
    for tugass in context['tugas']:
        deadlinelist.append(tugass.deadline)
        if pytz.utc.localize(datetime.now()) > tugass.deadline:
            deadlinetype.append('belumlewat')
        else:
            deadlinetype.append('sudahlewat')
    context['deadlinelist'] = deadlinelist
    context['deadlinetype'] = deadlinetype
    context['pointer'] = 0

    return render(request, 'jadwalku/perjadwal.html', context)

def message_post(request):
    if request.method == 'POST':
        form = Schedule_Form(request.POST)
        if form.is_valid():
            form.save()
            html = 'schedule.html'
            return redirect('' + '/schedule')
        else:
            return redirect('' + '/schedule')
    else:
        return render(request, 'jadwalku/schedule.html')

def delete(request, num):
    items = Schedule.objects.get(id=num)
    items.delete()
    return redirect('' + '/schedule')

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Valentino Herdyan Permadi' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2000,12,11) #TODO Implement this, format (Year, Month, Date)
npm = 1906350660 # TODO Implement this
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
    return render(request, 'lab_1/index.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

myweb/views.py
from django.shortcuts import render
from datetime import datetime, timedelta

def index(request):
    return render(request, 'myweb/home.html')

def time(request):
    return render(request, 'myweb/time.html', {'time': datetime.now() + timedelta(hours=7)})

def timezoned(request, zone):
    return render(request, 'myweb/time.html', {'zona' : datetime.now() + timedelta(hours=int(zone)+7)})

portfolio/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'myweb/index.html')

def hobby(request):
    return render(request, 'myweb/hobby.html')

jadwalku/templates/jadwalku/jadwalfull.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Schedule</title>
    <link href="https://fonts.googleapis.com/css?family=Rosario&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'myweb/img/resize-option.png' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <style>
        * {
            font-family: 'Rosario', sans-serif;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        {% for item in items %}
            <div>
                <a href="{{ item.id }}"><h1>{{ item.matkul }}</h1></a>
                <p>Jumlah SKS: {{ item.sks }}</p>
                <p>Ruangan: {{ item.ruangan }}</p>
            </div>
        {% endfor %}
        <a href="tambah"><button type="button" class="btn btn-outline-success">Tambah</button></a>
    </div>
</body>
</html>

jadwalku/templates/jadwalku/perjadwal.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Schedule</title>
    <link href="https://fonts.googleapis.com/css?family=Rosario&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'myweb/img/resize-option.png' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <style>
        * {
            font-family: 'Rosario', sans-serif;
        }
    </style>
</head>
<body>
        <a href="../schedule" style="color: black; text-decoration: none; opacity: 60%; margin-left: 20px;">Kembali</a>
    <div class="container-fluid">
        <h1>{{ items.matkul }}</h1>
        <h3>Pengajar: {{ items.pengajar }}</h3>
        <h3>Jumlah SKS: {{ items.sks }}</h3>
        <h3>Deskripsi: {{ items.desc }}</h3>
        <h3>Semester: {{ items.term }}</h3>
        <h3>Ruangan: {{ items.ruangan }}</h3>
        <a href="delete/{{ items.id }}"><button type="button" class="btn btn-outline-danger">Hapus</button></a>
        <hr>
        <h2>Tugas</h2>
        {% for banyaktugas in tugas %}
        
            <h4>{{ banyaktugas.judul_tugas }} </h4>
            <p>{{ banyaktugas.deadline }}</p>
        {% endfor %}
    </div>
</body>
</html>

jadwalku/templates/jadwalku/schedule.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Schedule</title>
    <link href="https://fonts.googleapis.com/css?family=Rosario&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'myweb/img/resize-option.png' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <style>
        * {
            font-family: 'Rosario', sans-serif;
        }
    </style>
</head>
<body>
    <a href="../schedule" style="color: black; text-decoration: none; opacity: 60%; margin-left: 20px;">Kembali</a>
    <div class="container-fluid">
        <form id="form" method="POST">
            {% csrf_token %}
            {{ schedule_form }}
            <label for="id_matkul">Mata Kuliah: </label>
            <input type="text" name="matkul" class="form-control" maxlength="40" id="id_matkul">
            <label for="id_pengajar">Dosen Pengajar: </label>
            <input type="text" name="pengajar" class="form-control" maxlength="40" id="id_pengajar">
            <label for="id_sks">Jumlah SKS: </label>
            <input type="text" name="sks" class="form-control" maxlength="40" id="id_sks">
            <label for="id_desc">Deskripsi: </label>
            <textarea name="desc" class="form-control" id="id_desc"></textarea>
            <label for="id_term">Term: </label>
            <input type="text" name="term" class="form-control" maxlength="40" id="id_term">
            <label for="id_ruangan">Ruangan: </label>
            <input type="text" name="ruangan" class="form-control" maxlength="40" id="id_ruangan">
            <button type="submit" class="btn btn-success">Submit</button>
        </form>
    </div>
</body>
</html>

lab_1/templates/lab_1/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ name }} | {{ npm }}</title>
    <link rel="stylesheet" href="{% static 'lab_1/default.css' %}" type="text/css">
    <link rel="icon" href="{% static 'lab_1/img/resize-option.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Cabin&display=swap" rel="stylesheet">
</head>
<body>
    <a href="../" style="color: black; text-decoration: none; opacity: 60%; margin-left: 20px;">Back</a>
    <div class="welcome">
        <h1>Welcome to my WebPage!</h1>
        <img src="{% static 'lab_1/img/mypic.jpg' %}" alt="gambar" class="mypic">
    </div>
    <div class="bio">
        <p>Hello! My name is {{name}}</p>
        <p>{{ npm }}</p>
        <p>Maung 2019</p>
        <p>Hobby : Gaming, Reading Manga, Watching Anime</p>
        <p>Short Description : <br>I am {{age}} years old. Reading Manga is one of my hobby.<br> I read popular shounen manga such as One Piece and Dr. Stone.<br> I am currently pursuing a Bachelor Degree in Computer Science<br> at Faculty of Computer Science, University of Indonesia.</p>
        <p>Education : <br>2019 - Present University of Indonesia<br>2016 - 2019 SMAN 1 Cikarang Utara<br>2013-2016 SMPN 1 Cikarang Utara<br>2007 - 2013 SD Permata Pertiwi</p>
        <p>You can find me at :</p>
    </div>
    <div class="socmed">
        <div class="ig"><a href="https://www.instagram.com/_drakoz/" target="_blank"><img src="{% static 'lab_1/img/ig.png' %}" class="img"></div></a>
        <div class="gitlab"><a href="https://gitlab.com/drakoz" target="_blank"><img src="{% static 'lab_1/img/gitlab.png' %}" class="img"></div></a>
    </div>
</body>
</html>

portfolio/templates/myweb/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Story 4 | Valentino Herdyan Permadi</title>
    <link href="https://fonts.googleapis.com/css?family=Rosario&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'myweb/img/resize-option.png' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <style>
        * {
            font-family: 'Rosario', sans-serif;
        }

        *[id]:before { 
            display: block; 
            content: " "; 
            margin-top: -40px; 
            height: 75px; 
            visibility: hidden; 
        }

        html{
            scroll-behavior: smooth;
        }
    </style>
</head>
<body>
</body>
</html>

portfolio/templates/myweb/hobby.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
{% include 'myweb/base.html' %}
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-sm navbar-light bg-white fixed-top">
            <a class="navbar-brand" href="../">Valentino</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="../portfolio">Home</a>
                    </li>
                </ul>
            </div>
        </nav>
        <h1 style="margin-top:100px;" class="text-center">My Hobby</h1>
        <!-- Button trigger modal -->
        <div class="text-center">
            <a class="btn" data-toggle="modal" data-target="#Modal" style="color:gray">
                don't click me
            </a>
        </div>
        
        <!-- Modal -->
        <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" style="height: auto;">
            <div class="modal-dialog modal-dialog-centered container-fluid" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">told ya don't</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                                  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                                  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                                </ol>
                                <div class="carousel-inner">
                                  <div class="carousel-item active">
                                    <img class="d-block w-100" src="{% static 'myweb/img/cursed1.jpg' %}" height="300px" alt="First slide">
                                  </div>
                                  <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static 'myweb/img/cursed2.jpg' %}" height="300px" alt="Second slide">
                                  </div>
                                  <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static 'myweb/img/cursed3.jpg' %}" height="300px" alt="Third slide">
                                  </div>
                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                  <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                  <span class="sr-only">Next</span>
                                </a>
                              </div>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
            </div>
        </div>
        <div class="card-deck" style="color: white; margin-top: 50px;">
            <div class="card" style="border: none;">
                <div class="card-body" style="background-color: #00A3FF;border-radius: 10px;">
                    <a href="https://myanimelist.net/manga/103897/Dr_Stone?suggestion=" target="_blank"><img src="{% static 'myweb/img/dr stone.jpg' %}" class="img-fluid mx-auto d-block" width="150px"></a>
                    <h3 class="card-text text-center" style="margin-top:10px">Reading Manga</h3>
                    <p class="card-text">Reading manga is one of my hobby. When there is a new update on mangas that i read, i spare some time to read them.</p>
                    <p class="card-text">
                        Current reading list:
                        <ul>
                            <li>One Piece</li>
                            <li>Dr. Stone</li>
                            <li>Darwin's Game</li>
                            <li>One Punch Man</li>
                            <li>Solo Leveling</li>
                            <li>Vinland Saga</li>
                        </ul>
                    </p>
                </div>
            </div>
            <div class="card" style="border: none;">
                <div class="card-body" style="background-color: #00A3FF;border-radius: 10px;">
                    <a href="https://myanimelist.net/anime/23321/Log_Horizon_2nd_Season" target="_blank"><img src="{% static 'myweb/img/log horizon.jpg' %}" class="img-fluid mx-auto d-block" width="150px"></a>
                    <h3 class="card-text text-center" style="margin-top:10px">Watching Anime</h3>
                    <p class="card-text">I watch anime when i have some time to spare. Unlike reading manga, i watch anime less often.</p>
                    <p class="card-text">
                        Current Watchlist:
                        <ul>
                            <li>Majutsushi Orphen Hagure Tabi</li>
                            <li>Darwin's Game</li>
                            <li>Pokemon (2019)</li>
                            <li>Log Horizon Season 2</li>
                            <li>Infinite Dendrogram</li>
                        </ul>
                    </p>
                </div>
            </div>
            <div class="card" style="border: none;">
                <div class="card-body" style="background-color: #00A3FF;border-radius: 10px;">
                    <a href="https://mojiken.itch.io/a-space" target="_blank"><img src="{% static 'myweb/img/a space for the unbound.jpg' %}" class="img-fluid mx-auto d-block" width="400px"></a>
                    <h3 class="card-text text-center" style="margin-top:10px">Playing Games</h3>
                    <p class="card-text">I don't play game often. But i like playing them. I am currently looking to play some indie games.</p>
                    <p class="card-text">
                        Current Wishlist:
                        <ul>
                            <li>Bastion</li>
                            <li>Owlboy</li>
                            <li>Roguelands</li>
                            <li>Noita</li>
                            <li>A Space For The Unbound</li>
                            <li>I am Jesus Christ</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

portfolio/templates/myweb/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home | Valentino Herdyan Permadi</title>
    <link href="https://fonts.googleapis.com/css?family=Rosario&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'myweb/img/resize-option.png' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <style>
        * {
            font-family: 'Rosario', sans-serif;
        }

        *[id]:before { 
            display: block; 
            content: " "; 
            margin-top: -40px; 
            height: 75px; 
            visibility: hidden; 
        }

        html{
            scroll-behavior: smooth;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <h1 class="text-center" style="margin-top:20vh">Welcome to my website</h1>
        <h3 class="text-center" style="opacity: 50%;">Valentino Herdyan Permadi</h3> 
        <button type="button" class="btn btn-primary btn-lg btn-block" style="margin-top: 20vh; " onclick="window.location.href = 'story_1';">Story 1</button>
        <button type="button" class="btn btn-primary btn-lg btn-block" onclick="window.location.href = 'portfolio';">Story 4</button>
    </div>
</body>
</html>

portfolio/templates/myweb/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-white fixed-top">
        <a class="navbar-brand" href="../">Valentino</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#Home">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#About">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#Experiences">Experiences</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#Contact">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="hobby">Hobby</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}{% endblock %}
</body>
</html>

portfolio/templates/myweb/time.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Current Time</title>
</head>
<body>
    {{ time }}
    {{ zona }}
</body>
</html>